<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class District extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'code',
        'city_id',
        'url'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (District $district) {
            $district->slug = Str::uuid()->toString();
        });
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    // TODO Scope
    public function scopeFilterByCode(Builder $query, $code): Builder
    {
        return $query->where('code', $code);
    }
}
