<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Str;

class FormOfEducation extends Model
{
    protected $fillable = [
        'slug',
        'code',
        'name',
        'education_unit_id'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (FormOfEducation $formOfEducation) {
            $formOfEducation->slug = Str::uuid()->toString();
        });
    }

    public function educationUnit(): BelongsTo
    {
        return $this->belongsTo(EducationUnit::class);
    }

    // TODO Scope
    public function scopeFilterBySlug(Builder $query, $slug): Builder
    {
        return $query->where('slug', $slug);
    }

    public function scopeFilterData(Builder $query, $request): Builder
    {
        $search = $request['search'] ?? null;
        $groupLevel = $request['group_level'] ?? null;

        return $query->when($search, fn($query) => $query->whereLike('name', "%$search%"))
            ->when($groupLevel, fn($query) => $query->whereIn('name', $groupLevel));
    }
}
