<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class School extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'npsn',
        'street',
        'village',
        'status',
        'district_id',
        'form_of_education_id',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (School $school) {
            $school->slug = Str::uuid()->toString();
        });
    }

    // TODO Scope
    public function scopeFilterByNpsn(Builder $query, $npsn): Builder
    {
        return $query->where('npsn', $npsn);
    }
}
